"""Export endpoints — PDF and Markdown download."""
import io
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse

from ..repositories.runs_repo import get_run
from ..logger import get_logger


router = APIRouter()
logger = get_logger(__name__)


@router.get("/runs/{run_id}/export/markdown")
async def export_markdown(run_id: str):
    """Export run output as a Markdown file."""
    run = await get_run(run_id)
    if not run:
        raise HTTPException(status_code=404, detail="Run not found.")

    output = run.get("final_output", "")
    if not output:
        raise HTTPException(status_code=404, detail="Run has no output yet.")

    goal = run.get("goal", "Research")
    content = f"# ARIA Report\n\n**Goal:** {goal}\n\n---\n\n{output}"

    return StreamingResponse(
        io.BytesIO(content.encode("utf-8")),
        media_type="text/markdown",
        headers={
            "Content-Disposition": f'attachment; filename="aria-report-{run_id[:8]}.md"'
        },
    )


@router.get("/runs/{run_id}/export/pdf")
async def export_pdf(run_id: str):
    """Export run output as a PDF file."""
    run = await get_run(run_id)
    if not run:
        raise HTTPException(status_code=404, detail="Run not found.")

    output = run.get("final_output", "")
    if not output:
        raise HTTPException(status_code=404, detail="Run has no output yet.")

    goal = run.get("goal", "Research")

    try:
        pdf_bytes = _markdown_to_pdf(output, goal)
        return StreamingResponse(
            io.BytesIO(pdf_bytes),
            media_type="application/pdf",
            headers={
                "Content-Disposition": f'attachment; filename="aria-report-{run_id[:8]}.pdf"'
            },
        )
    except ImportError:
        logger.warning("PDF export requested but xhtml2pdf is not installed.")
        raise HTTPException(
            status_code=501,
            detail="PDF export requires xhtml2pdf. Install with: pip install xhtml2pdf"
        )
    except Exception as e:
        logger.error(f"PDF generation failed: {e}")
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {str(e)}")


def _markdown_to_pdf(markdown_text: str, goal: str) -> bytes:
    """Convert markdown to PDF using xhtml2pdf."""
    import markdown
    from xhtml2pdf import pisa

    # Convert markdown to HTML
    html_body = markdown.markdown(
        markdown_text,
        extensions=["tables", "fenced_code", "codehilite"],
    )

    # Wrap in styled HTML
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{
                font-family: 'Helvetica', 'Arial', sans-serif;
                font-size: 11px;
                line-height: 1.6;
                color: #1a1a1a;
                margin: 40px;
            }}
            h1 {{ color: #0A0E1A; font-size: 22px; border-bottom: 2px solid #3B82F6; padding-bottom: 8px; }}
            h2 {{ color: #1E2D4A; font-size: 16px; margin-top: 20px; }}
            h3 {{ color: #475569; font-size: 13px; }}
            code {{ background: #f1f5f9; padding: 2px 6px; border-radius: 3px; font-family: monospace; font-size: 10px; }}
            pre {{ background: #f1f5f9; padding: 12px; border-radius: 6px; border: 1px solid #e2e8f0; }}
            pre code {{ background: none; padding: 0; }}
            table {{ border-collapse: collapse; width: 100%; margin: 10px 0; }}
            th, td {{ border: 1px solid #e2e8f0; padding: 8px; text-align: left; font-size: 10px; }}
            th {{ background: #f1f5f9; font-weight: bold; }}
            blockquote {{ border-left: 3px solid #3B82F6; padding-left: 12px; color: #64748b; margin: 10px 0; }}
            ul, ol {{ padding-left: 20px; }}
            li {{ margin: 4px 0; }}
            .header {{ text-align: center; margin-bottom: 30px; color: #475569; }}
            .footer {{ text-align: center; margin-top: 30px; color: #94a3b8; font-size: 9px; border-top: 1px solid #e2e8f0; padding-top: 10px; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>ARIA Report</h1>
            <p><strong>Goal:</strong> {goal}</p>
        </div>
        {html_body}
        <div class="footer">
            Generated by ARIA
        </div>
    </body>
    </html>
    """

    result = io.BytesIO()
    pisa.CreatePDF(io.BytesIO(html.encode("utf-8")), dest=result)
    return result.getvalue()
